"""
NepalMed AI: Clinical Referral Generator
Produces professional referral letters based on AI assessment and triage results.
"""

import datetime

class ReferralGenerator:
    def __init__(self, hospital_name="NepalMed AI Virtual Clinic"):
        self.hospital_name = hospital_name

    def generate_note(self, patient_data, triage_result, lab_summary=None):
        """
        Generates a structured referral note.
        """
        date_str = datetime.date.today().strftime("%d %B %Y")
        
        note = f"""
REFERRAL LETTER
Date: {date_str}
From: {self.hospital_name}
To: The Medical Officer / Consultant In-Charge

Subject: Referral of Patient for Further Evaluation and Management

Patient Name: {patient_data.get('name', 'N/A')}
Age/Gender: {patient_data.get('age', 'N/A')} / {patient_data.get('gender', 'N/A')}
District: {patient_data.get('district', 'N/A')}

CLINICAL SUMMARY:
The patient presented with the following symptoms:
{patient_data.get('symptoms', 'No symptoms recorded.')}

AI TRIAGE ASSESSMENT:
- Priority Level: {triage_result.get('triage_level', 'ROUTINE')}
- Reason for Referral: {triage_result.get('reason', 'N/A')}

LABORATORY FINDINGS (if available):
{lab_summary if lab_summary else 'No laboratory data provided.'}

RECOMMENDED ACTION:
{triage_result.get('advice', 'Please evaluate according to standard clinical protocols.')}

This referral was generated by NepalMed AI based on National Standard Treatment Protocols (STP 2078). 
Please correlate with clinical findings.

Signature: __________________________
(Authorized Personnel)
        """
        return note.strip()

if __name__ == "__main__":
    gen = ReferralGenerator()
    patient = {"name": "Ram Bahadur", "age": 45, "gender": "Male", "district": "Saptari", "symptoms": "Fever and splenomegaly"}
    triage = {"triage_level": "URGENT", "reason": "Suspected Kala-azar", "advice": "Refer for rK39 testing."}
    print(gen.generate_note(patient, triage))
